In [13]:
import numpy as np
# 2-d arrays
x=[[10,1,2],[3,8,5],[6,10,8]]
ar1 = np.array(x)
ar1

array([[10,  1,  2],
       [ 3,  8,  5],
       [ 6, 10,  8]])

In [14]:
# attributes
ar1.shape
ar1.dtype
ar1.size

9

In [19]:
# min,max,sort
ar1.argmax(axis=0)
ar1.argmax(axis=1)

array([0, 1, 1], dtype=int64)

In [20]:
ar1.argmin(axis=1)
ar1.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [22]:
ar1.argsort()

array([[1, 2, 0],
       [0, 2, 1],
       [0, 2, 1]], dtype=int64)

In [26]:
# sum
ar1.sum(axis=1)
ar1.sum(axis=0)

array([19, 19, 15])

In [28]:
# transpose
ar1.T

array([[10,  3,  6],
       [ 1,  8, 10],
       [ 2,  5,  8]])

In [31]:
print(ar1.flat)

In [34]:
for i in ar1.flat:
    print(i)

10
1
2
3
8
5
6
10
8


In [36]:
ar1.ndim

2

In [38]:
ar1.nbytes

36