In [3]:
# array creation methods
# 1.list/tuple/set to array
import numpy as np
ar1=np.array([1,2,3,4,5])
print('list-array: ',ar1)
ar1=np.array((1,2,3,4,5,2,1,3,4,5,6,7))
print('tuple-array: ',ar1)
ar1=np.array({1,2,3,4,5,6,7})
print('set-array: ',ar1)

list-array:  [1 2 3 4 5]
tuple-array:  [1 2 3 4 5 2 1 3 4 5 6 7]
set-array:  {1, 2, 3, 4, 5, 6, 7}


In [14]:
# 2. intrensic conversion
import numpy as np
ar1 = np.zeros(3) # 1-d array
print("1-d array : ",ar1)
ar2 = np.zeros((3,3))
print("2-d array : ",ar2)

1-d array :  [0. 0. 0.]
2-d array :  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# 3. creation of lists using arange function
ar3 = np.arange(15)
print(ar3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [22]:
# 4. linspace --> returns linear spaced elements in specied range
ar5 = np.linspace(1,100,5)
print(ar5)

[  1.    25.75  50.5   75.25 100.  ]


In [30]:
# 5. empty/random-array --> filled with zeros and ones
ar6 = np.empty(15) # array of 15 elements
print(ar6)
ar7 = np.empty((3,3)) # array with random values and withn,n diemensions
print(ar7)

[4.67296746e-307 1.69121096e-306 2.78146455e-307 8.34441742e-308
 1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307
 7.56594375e-307 6.23060065e-307 1.78021527e-306 8.34454050e-308
 1.11261027e-306 2.04712907e-306 5.74802010e+294]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
# empty_like mwthod
# 1-d array
x = np.array([1,2,3,4,5,6,7,8])
ar8 = np.empty_like(x)
print(ar8)
# 2-d array
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar8 = np.empty_like(x)
print(ar8)

[1 2 3 4 5 6 7 8]
[[-285262720      32765   83317584]
 [       438   83316224        438]
 [  83316944        438    4259926]]


In [43]:
# identity
ar9 = np.identity(99)
print(ar9)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [60]:
# nd-1d
ar9.ravel
ar9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [61]:
# 1d - nd
# reshape
ar9 = np.arange(99)
ar9.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])